#
# Makefile to clean the testing directory - deletes all test output files
# except for results.html
#
# Last Revised: 17 Sep 2019 (SYZ) - Initial.
#                8 Sep 2021 (SYZ) - Change from Postscript to SVG.
#                9 Sep 2021 (SYZ) - Delete more output files.
#

clean:
	@rm -f ?dump_??? ?dump_????
	@rm -f ccoev cdump???avg_???
	@rm -f gem????_???
	@rm -f plot_???.html cluster_example.html trajfreq.html
	@rm -f plot_???.ps cluster_example.ps trajfreq.ps
	@rm -f ccrop_??? HYSPLIT_???.kmz
	@rm -f stat_???.txt
	@rm -f CONC.??? MESSAGE.??? VMSDIST.??? WARNING.??? PARDUMP.???
	@rm -f ERROR_LOG.txt WARNING message.txt
	@rm -f grun_*.log grun_*.ps grun_*.html
