#define ASSERT_EQ2(a, b)            ASSERT_EQ(__FILE__, __LINE__, a, b)
#define ASSERT_GT2(a, b)            ASSERT_GT(__FILE__, __LINE__, a, b)
#define ASSERT_LT2(a, b)            ASSERT_LT(__FILE__, __LINE__, a, b)
#define ASSERT_GE2(a, b)            ASSERT_GE(__FILE__, __LINE__, a, b)
#define ASSERT_LE2(a, b)            ASSERT_LE(__FILE__, __LINE__, a, b)
#define ASSERT_FLOAT_EQ2(a, b)      ASSERT_FLOAT_EQ(__FILE__, __LINE__, a, b)
#define ASSERT_FLOAT_EQ3(a, b, c)   ASSERT_FLOAT_EQ(__FILE__, __LINE__, a, b, c)
#define ASSERT_DOUBLE_EQ2(a, b)     ASSERT_DOUBLE_EQ(__FILE__, __LINE__, a, b)
#define ASSERT_DOUBLE_EQ3(a, b, c)  ASSERT_DOUBLE_EQ(__FILE__, __LINE__, a, b, c)
#define ASSERT_TRUE1(a)             ASSERT_TRUE(__FILE__, __LINE__, a)
#define ASSERT_FALSE1(a)            ASSERT_FALSE(__FILE__, __LINE__, a)
#define ASSERT_STR_EQ2(a, b)        ASSERT_STR_EQ(__FILE__, __LINE__, a, b)
